//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MediaRevCo.Business.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MediaRevCoEntityModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MediaRevCoEntityModelContainer object using the connection string found in the 'MediaRevCoEntityModelContainer' section of the application configuration file.
        /// </summary>
        public MediaRevCoEntityModelContainer() : base("name=MediaRevCoEntityModelContainer", "MediaRevCoEntityModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaRevCoEntityModelContainer object.
        /// </summary>
        public MediaRevCoEntityModelContainer(string connectionString) : base(connectionString, "MediaRevCoEntityModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaRevCoEntityModelContainer object.
        /// </summary>
        public MediaRevCoEntityModelContainer(EntityConnection connection) : base(connection, "MediaRevCoEntityModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Review> Reviews
        {
            get
            {
                if ((_Reviews == null))
                {
                    _Reviews = base.CreateObjectSet<Review>("Reviews");
                }
                return _Reviews;
            }
        }
        private ObjectSet<Review> _Reviews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MediaRevCoEntityModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="reviewTitle">Initial value of the ReviewTitle property.</param>
        /// <param name="comments">Initial value of the Comments property.</param>
        /// <param name="mediaItemTitle">Initial value of the MediaItemTitle property.</param>
        /// <param name="uPC">Initial value of the UPC property.</param>
        public static Review CreateReview(global::System.Int32 id, global::System.String reviewTitle, global::System.String comments, global::System.String mediaItemTitle, global::System.String uPC)
        {
            Review review = new Review();
            review.Id = id;
            review.ReviewTitle = reviewTitle;
            review.Comments = comments;
            review.MediaItemTitle = mediaItemTitle;
            review.UPC = uPC;
            return review;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReviewTitle
        {
            get
            {
                return _ReviewTitle;
            }
            set
            {
                OnReviewTitleChanging(value);
                ReportPropertyChanging("ReviewTitle");
                _ReviewTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReviewTitle");
                OnReviewTitleChanged();
            }
        }
        private global::System.String _ReviewTitle;
        partial void OnReviewTitleChanging(global::System.String value);
        partial void OnReviewTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaItemTitle
        {
            get
            {
                return _MediaItemTitle;
            }
            set
            {
                OnMediaItemTitleChanging(value);
                ReportPropertyChanging("MediaItemTitle");
                _MediaItemTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MediaItemTitle");
                OnMediaItemTitleChanged();
            }
        }
        private global::System.String _MediaItemTitle;
        partial void OnMediaItemTitleChanging(global::System.String value);
        partial void OnMediaItemTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UPC
        {
            get
            {
                return _UPC;
            }
            set
            {
                OnUPCChanging(value);
                ReportPropertyChanging("UPC");
                _UPC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UPC");
                OnUPCChanged();
            }
        }
        private global::System.String _UPC;
        partial void OnUPCChanging(global::System.String value);
        partial void OnUPCChanged();

        #endregion
    
    }

    #endregion
    
}
