//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Business.Components.TransferNotificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransferNotificationService.ITransferNotificationService")]
    public interface ITransferNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransferNotificationService/NotifyTransferOutcome")]
        void NotifyTransferOutcome(bool pOutcome, string pMessage, string pDescription);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransferNotificationServiceChannel : Bank.Business.Components.TransferNotificationService.ITransferNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferNotificationServiceClient : System.ServiceModel.ClientBase<Bank.Business.Components.TransferNotificationService.ITransferNotificationService>, Bank.Business.Components.TransferNotificationService.ITransferNotificationService {
        
        public TransferNotificationServiceClient() {
        }
        
        public TransferNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NotifyTransferOutcome(bool pOutcome, string pMessage, string pDescription) {
            base.Channel.NotifyTransferOutcome(pOutcome, pMessage, pDescription);
        }
    }
}
